SELECT DISTINCT
    HEADER.segment1 AS "Order",
    REPLACE(TRIM(HEADER.COMMENTS), CHR(10), ' ') AS "Description",
    TO_CHAR(HEADER.creation_date, 'YYYY/MM/DD') AS creation_date,
    HEADER.DOCUMENT_STATUS AS "Header Status",
    PROCUREMENT_BUSINESS_UNIT_TL.NAME AS "Procurement BU",
    REQUISITIONING_BU_TL.NAME AS "Requisitioning BU",
    SUPPLIER.VENDOR_NAME AS "Supplier",
    SUPPLIER_SITE.VENDOR_SITE_CODE AS "Supplier Site",
    '' AS "supplier order",
    '' AS "supplier contact",
    xle.name AS "sold to legal entity",
    HEADER.SUPPLIER_NOTIF_METHOD AS "Communication Method",
    BILL_TO_LOCATION.LOCATION_CODE AS "Bill To Location",
    NVL((
            SELECT MAX(hl.description)
            FROM hr_locations_all_f_vl hl
            WHERE hl.location_id = pola.ship_to_location_id
        ), (
            SELECT MAX(address1 || '' || city || ',' || STATE || postal_code)
            FROM hz_locations hl
            WHERE hl.location_id = pola.ship_to_cust_location_id
        )) AS "Ship-to Location",
    HEADER.GROUP_REQUISITIONS AS "REQUISITIONS",
    BUYER_NAME.FULL_NAME AS "Buyer",
    LINE.TAX_EXCLUSIVE_PRICE AS "TOTAL TAX",
    TOTAL.TOTAL_ASSESSABLE_VALUE AS "Ordered",
    TOTAL.TOTAL_ASSESSABLE_VALUE AS "Total",
    TERM_TL.NAME AS "Payment Terms",
    HEADER.MODE_OF_TRANSPORT AS "Shipping Method",
    HEADER.FREIGHT_TERMS_LOOKUP_CODE AS "Freight Terms",
    HEADER.FOB_LOOKUP_CODE AS "Fob",
    HEADER.PAY_ON_USE_FLAG AS "Pay On Receipt",
    HEADER.CONFIRMING_ORDER_FLAG AS "Confirming order",
    HEADER.ATTRIBUTE1 AS "Capital Expenditure Type",
    REPLACE(TRIM(HEADER.NOTE_TO_VENDOR), CHR(10), ' ') AS "Note to Supplier",
    REPLACE(TRIM(HEADER.NOTE_TO_RECEIVER), CHR(10), ' ') AS "Note to Receiver"


FROM
    PO_HEADERS_ALL HEADER
    LEFT JOIN PO_LINES_ALL LINE 
        ON HEADER.PO_HEADER_ID = LINE.PO_HEADER_ID
    LEFT JOIN PO_LINE_LOCATIONS_ALL LINE_LOCATION 
        ON LINE.PO_LINE_ID = LINE_LOCATION.PO_LINE_ID
    LEFT JOIN XLE_ENTITY_PROFILES XLE 
        ON HEADER.SOLDTO_LE_ID = XLE.LEGAL_ENTITY_ID
    LEFT JOIN PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE 
        ON HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
    LEFT JOIN PO_DOC_STYLE_HEADERS DOCUMENT_STYLE 
        ON HEADER.STYLE_ID = DOCUMENT_STYLE.STYLE_ID
    LEFT JOIN HR_ORGANIZATION_UNITS_F_TL PROCUREMENT_BUSINESS_UNIT_TL 
        ON HEADER.PRC_BU_ID = PROCUREMENT_BUSINESS_UNIT_TL.ORGANIZATION_ID
        AND PROCUREMENT_BUSINESS_UNIT_TL.LANGUAGE = 'US'
    LEFT JOIN HR_ORGANIZATION_UNITS_F_TL REQUISITIONING_BU_TL 
        ON HEADER.REQ_BU_ID = REQUISITIONING_BU_TL.ORGANIZATION_ID
        AND REQUISITIONING_BU_TL.LANGUAGE = 'US'
    LEFT JOIN HR_ORGANIZATION_UNITS_F_TL BILL_TO_BU_TL 
        ON HEADER.BILLTO_BU_ID = BILL_TO_BU_TL.ORGANIZATION_ID
        AND BILL_TO_BU_TL.LANGUAGE = 'US'
    LEFT JOIN (
        SELECT DISTINCT
            PERSON_ID,
            FULL_NAME
        FROM
            PER_PERSON_NAMES_F
        WHERE
            NAME_TYPE = 'US'
    ) BUYER_NAME ON HEADER.AGENT_ID = BUYER_NAME.PERSON_ID
    LEFT JOIN POZ_SUPPLIERS_SIMPLE_V SUPPLIER 
        ON HEADER.VENDOR_ID = SUPPLIER.VENDOR_ID
    LEFT JOIN POZ_SUPPLIER_SITES_ALL_M SUPPLIER_SITE 
        ON HEADER.VENDOR_SITE_ID = SUPPLIER_SITE.VENDOR_SITE_ID
    LEFT JOIN HZ_PARTIES FREIGHT_CARRIER 
        ON HEADER.CARRIER_ID = FREIGHT_CARRIER.PARTY_ID
    LEFT JOIN AP_TERMS_TL TERM_TL 
        ON HEADER.TERMS_ID = TERM_TL.TERM_ID
        AND TERM_TL.LANGUAGE = 'US'
    LEFT JOIN HR_LOCATIONS_ALL BILL_TO_LOCATION 
        ON HEADER.BILL_TO_LOCATION_ID = BILL_TO_LOCATION.LOCATION_ID
    LEFT JOIN HR_LOCATIONS_ALL SHIP_TO_LOCATION 
        ON HEADER.SHIP_TO_LOCATION_ID = SHIP_TO_LOCATION.LOCATION_ID
    LEFT JOIN (
        SELECT
            HEADER.segment1 AS "Order",
            SUM(LINE_LOCATION.ASSESSABLE_VALUE) AS TOTAL_ASSESSABLE_VALUE
        FROM
            PO_HEADERS_ALL HEADER
            LEFT JOIN PO_LINES_ALL LINE 
                ON HEADER.PO_HEADER_ID = LINE.PO_HEADER_ID
            LEFT JOIN PO_LINE_LOCATIONS_ALL LINE_LOCATION 
                ON LINE.PO_LINE_ID = LINE_LOCATION.PO_LINE_ID
        GROUP BY
            SEGMENT1
    ) TOTAL ON HEADER.segment1 = TOTAL."Order"
    LEFT JOIN (
        SELECT DISTINCT
            PERSON_ID,
            EMAIL_ADDRESS
        FROM
            PER_EMAIL_ADDRESSES
    ) BUYER_EMAIL ON HEADER.AGENT_ID = BUYER_EMAIL.PERSON_ID
    LEFT JOIN po_line_locations_all pola 
        ON LINE.po_line_id = pola.po_line_id
WHERE
    HEADER.DOCUMENT_STATUS = 'OPEN'
    AND LINE_LOCATION.ASSESSABLE_VALUE <> '0'

