select distinct
DISTRIBUTION.PO_DISTRIBUTION_ID as "Interface Distribution Key",
DISTRIBUTION.LINE_LOCATION_ID  as  "Interface Line Location Key",
DISTRIBUTION.DISTRIBUTION_NUM as "Distribution",
DELIVER_TO_LOCATION.LOCATION_CODE as "Deliver-to Location",
REQUESTER_NAME.FULL_NAME as "Requester",
DISTRIBUTION.DESTINATION_SUBINVENTORY as "Subinventory",
LINE_LOCATION.ASSESSABLE_VALUE as "AMOUNT",
DISTRIBUTION.SHIPPING_UOM_QUANTITY as "Quantity",
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT1 as "CHARGE_ACCOUNT_SEGMENT1",
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT2 as "CHARGE_ACCOUNT_SEGMENT2", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT3 as "CHARGE_ACCOUNT_SEGMENT3", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT4 as "CHARGE_ACCOUNT_SEGMENT4", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT5 as "CHARGE_ACCOUNT_SEGMENT5", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT6 as "CHARGE_ACCOUNT_SEGMENT6", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT7 as "CHARGE_ACCOUNT_SEGMENT7", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT8 as "CHARGE_ACCOUNT_SEGMENT8",
'' as "CHARGE_ACCOUNT_SEGMENT9", 
'' as "CHARGE_ACCOUNT_SEGMENT10", 
'' as "CHARGE_ACCOUNT_SEGMENT11", 
'' as "CHARGE_ACCOUNT_SEGMENT12", 
'' as "CHARGE_ACCOUNT_SEGMENT13", 
'' as "CHARGE_ACCOUNT_SEGMENT14", 
'' as "CHARGE_ACCOUNT_SEGMENT15", 
'' as "CHARGE_ACCOUNT_SEGMENT16", 
'' as "CHARGE_ACCOUNT_SEGMENT17", 
'' as "CHARGE_ACCOUNT_SEGMENT18", 
'' as "CHARGE_ACCOUNT_SEGMENT19", 
'' as "CHARGE_ACCOUNT_SEGMENT20", 
'' as "CHARGE_ACCOUNT_SEGMENT21", 
'' as "CHARGE_ACCOUNT_SEGMENT22", 
'' as "CHARGE_ACCOUNT_SEGMENT23", 
'' as "CHARGE_ACCOUNT_SEGMENT24", 
'' as "CHARGE_ACCOUNT_SEGMENT25", 
'' as "CHARGE_ACCOUNT_SEGMENT26", 
'' as "CHARGE_ACCOUNT_SEGMENT27", 
'' as "CHARGE_ACCOUNT_SEGMENT28", 
'' as "CHARGE_ACCOUNT_SEGMENT29", 
'' as "CHARGE_ACCOUNT_SEGMENT30", 
LINE_LOCATION.DESTINATION_TYPE_CODE as "Destination CONTEXT",
DISTRIBUTION.PJC_PROJECT_ID as "Project Number",
DISTRIBUTION.PJC_TASK_ID as "Task Number",
DISTRIBUTION.PJC_EXPENDITURE_ITEM_DATE as "Expenditure Item Date",
DISTRIBUTION.PJC_EXPENDITURE_TYPE_ID as "Expenditure Type",
DISTRIBUTION.PJC_ORGANIZATION_ID as "Expenditure Organization",
'' as "Billable",
DISTRIBUTION.PJC_CAPITALIZABLE_FLAG as "Capitalizable",
DISTRIBUTION.PJC_WORK_TYPE_ID as "Work Type", -- counts to 0
'' as "PJC_RESERVED_ATTRIBUTE1",
'' as "PJC_RESERVED_ATTRIBUTE2",
'' as "PJC_RESERVED_ATTRIBUTE3",
'' as "PJC_RESERVED_ATTRIBUTE4",
'' as "PJC_RESERVED_ATTRIBUTE5",
'' as "PJC_RESERVED_ATTRIBUTE6",
'' as "PJC_RESERVED_ATTRIBUTE7",
'' as "PJC_RESERVED_ATTRIBUTE8",
'' as "PJC_RESERVED_ATTRIBUTE9",
'' as "PJC_RESERVED_ATTRIBUTE10",
'' as "PJC_USER_DEF_ATTRIBUTE1",
'' as "PJC_USER_DEF_ATTRIBUTE2",
'' as "PJC_USER_DEF_ATTRIBUTE3",
'' as "PJC_USER_DEF_ATTRIBUTE4",
'' as "PJC_USER_DEF_ATTRIBUTE5",
'' as "PJC_USER_DEF_ATTRIBUTE6",
'' as "PJC_USER_DEF_ATTRIBUTE7",
'' as "PJC_USER_DEF_ATTRIBUTE8",
'' as "PJC_USER_DEF_ATTRIBUTE9",
'' as "PJC_USER_DEF_ATTRIBUTE10",
DISTRIBUTION.Rate as "Rate",
DISTRIBUTION.RATE_DATE as "RATE Date",
'' as "ATTRIBUTE_CATEGORY",
DISTRIBUTION.ATTRIBUTE1 as "ATTRIBUTE1",
'' as "ATTRIBUTE2",
'' as "ATTRIBUTE3",
'' as "ATTRIBUTE4",
'' as "ATTRIBUTE5",
'' as "ATTRIBUTE6",
'' as "ATTRIBUTE7",
'' as "ATTRIBUTE8",
'' as "ATTRIBUTE9",
'' as "ATTRIBUTE10",
'' as "ATTRIBUTE11",
'' as "ATTRIBUTE12",
'' as "ATTRIBUTE13",
'' as "ATTRIBUTE14",
'' as "ATTRIBUTE15",
'' as "ATTRIBUTE16",
'' as "ATTRIBUTE17",
'' as "ATTRIBUTE18",
'' as "ATTRIBUTE19",
'' as "ATTRIBUTE20",
'' as "ATTRIBUTE_DATE1",
'' as "ATTRIBUTE_DATE2",
'' as "ATTRIBUTE_DATE3",
'' as "ATTRIBUTE_DATE4",
'' as "ATTRIBUTE_DATE5",
'' as "ATTRIBUTE_DATE6",
'' as "ATTRIBUTE_DATE7",
'' as "ATTRIBUTE_DATE8",
'' as "ATTRIBUTE_DATE9",
'' as "ATTRIBUTE_DATE10",
'' as "ATTRIBUTE_NUMBER1",
'' as "ATTRIBUTE_NUMBER2",
'' as "ATTRIBUTE_NUMBER3",
'' as "ATTRIBUTE_NUMBER4",
'' as "ATTRIBUTE_NUMBER5",
'' as "ATTRIBUTE_NUMBER6",
'' as "ATTRIBUTE_NUMBER7",
'' as "ATTRIBUTE_NUMBER8",
'' as "ATTRIBUTE_NUMBER9",
'' as "ATTRIBUTE_NUMBER10",
'' as "ATTRIBUTE_TIMESTAMP1",
'' as "ATTRIBUTE_TIMESTAMP2",
'' as "ATTRIBUTE_TIMESTAMP3",
'' as "ATTRIBUTE_TIMESTAMP4",
'' as "ATTRIBUTE_TIMESTAMP5",
'' as "ATTRIBUTE_TIMESTAMP6",
'' as "ATTRIBUTE_TIMESTAMP7",
'' as "ATTRIBUTE_TIMESTAMP8",
'' as "ATTRIBUTE_TIMESTAMP9",
'' as "ATTRIBUTE_TIMESTAMP10",
'' as "Requester E-mail",
DISTRIBUTION.BUDGET_DATE as "Budget Date",
LINE.CONTRACT_ID as "Contract Number",
'' as "Funding Source",
'' as "GLOBAL_ATTRIBUTE1"



from

PO_DISTRIBUTIONS_ALL DISTRIBUTION
    
    left join GL_CODE_COMBINATIONS CHARGE_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.CODE_COMBINATION_ID = CHARGE_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID
    
    left join GL_CODE_COMBINATIONS ACCRUAL_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.ACCRUAL_ACCOUNT_ID = ACCRUAL_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID
    
    left join GL_CODE_COMBINATIONS VARIANCE_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.VARIANCE_ACCOUNT_ID = VARIANCE_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID

    left join PO_HEADERS_ALL HEADER
        on DISTRIBUTION.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and DISTRIBUTION.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    LEFT JOIN PO_LINE_LOCATIONS_ALL LINE_LOCATION
        ON DISTRIBUTION.LINE_LOCATION_ID = LINE_LOCATION.LINE_LOCATION_ID
    left join HR_LOCATIONS_ALL DELIVER_TO_LOCATION
        on DISTRIBUTION.DELIVER_TO_LOCATION_ID = DELIVER_TO_LOCATION.LOCATION_ID
    LEFT JOIN PO_LINES_ALL LINE
       ON LINE_LOCATION.PO_LINE_ID = LINE.PO_LINE_ID
    LEFT JOIN egp_system_items EGP
        on LINE.ITEM_ID = EGP.INVENTORY_ITEM_ID
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) REQUESTER_NAME
        on DISTRIBUTION.DELIVER_TO_PERSON_ID = REQUESTER_NAME.PERSON_ID
    left join EGP_CATEGORIES_TL CATEGORIES
        on LINE.CATEGORY_ID = CATEGORIES.CATEGORY_ID
where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and LINE_LOCATION.ASSESSABLE_VALUE <> '0'




