select distinct

LINE.PO_LINE_ID as "Interface Line Key" ,
LINE.PO_HEADER_ID as "Interface Header Key",
'ADD' as "Action",
LINE.LINE_NUM as "Line",
LINE_TYPE.LINE_TYPE_CODE as "Line Type",
EGP.ITEM_NUMBER as "ITEM",
REPLACE(TRIM(LINE.ITEM_DESCRIPTION),CHR(10),' ')  as "Item Description",
LINE.ITEM_REVISION as "Item REVISION",
CATEGORIES.category_name as "Category name",
LINE_LOCATION.ASSESSABLE_VALUE as "AMOUNT",
LINE.QUANTITY as "Quantity",
LINE.SHIPPING_UOM_CODE as "UOM",
LINE.unit_PRICE as "Price",
LINE.SECONDARY_QUANTITY as "SECONDARY QUANTITY",
LINE.SECONDARY_UOM_CODE as "SECONDARY UOM",
LINE.VENDOR_PRODUCT_NUM as "Supplier Item",
LINE.NEGOTIATED_BY_PREPARER_FLAG as "Negotiated",
LINE.HAZARD_CLASS_ID as "HAZARD CLASS",
UN_NUMBER.UN_NUMBER_CODE as "UN_NUMBER",
REPLACE(TRIM(HEADER.NOTE_TO_VENDOR),CHR(10),' ') AS "Note to Supplier",
REPLACE(TRIM(HEADER.NOTE_TO_RECEIVER),CHR(10),' ') as "Note to Receiver",
'' as "ATTRIBUTE_CATEGORY",
'' as "ATTRIBUTE1",
'' as "ATTRIBUTE2",
LINE.ATTRIBUTE1 as "ATTRIBUTE3",
LINE.ATTRIBUTE2 as "ATTRIBUTE4",
LINE.ATTRIBUTE3 as "ATTRIBUTE5",
'' as "ATTRIBUTE6",
'' as "ATTRIBUTE7",
'' as "ATTRIBUTE8",
'' as "ATTRIBUTE9",
'' as "ATTRIBUTE10",
'' as "ATTRIBUTE11",
'' as "ATTRIBUTE12",
'' as "ATTRIBUTE13",
'' as "ATTRIBUTE14",
'' as "ATTRIBUTE15",
'' as "ATTRIBUTE16",
'' as "ATTRIBUTE17",
'' as "ATTRIBUTE18",
'' as "ATTRIBUTE19",
'' as "ATTRIBUTE20",
'' as "ATTRIBUTE_DATE1", 
'' as "ATTRIBUTE_DATE2", 
'' as "ATTRIBUTE_DATE3", 
'' as "ATTRIBUTE_DATE4", 
'' as "ATTRIBUTE_DATE5", 
'' as "ATTRIBUTE_DATE6", 
'' as "ATTRIBUTE_DATE7", 
'' as "ATTRIBUTE_DATE8", 
'' as "ATTRIBUTE_DATE9", 
'' as "ATTRIBUTE_DATE10",
'' as "ATTRIBUTE_NUMBER1",
'' as "ATTRIBUTE_NUMBER2",
'' as "ATTRIBUTE_NUMBER3",
'' as "ATTRIBUTE_NUMBER4",
'' as "ATTRIBUTE_NUMBER5",
'' as "ATTRIBUTE_NUMBER6",
'' as "ATTRIBUTE_NUMBER7",
'' as "ATTRIBUTE_NUMBER8",
'' as "ATTRIBUTE_NUMBER9",
'' as "ATTRIBUTE_NUMBER10",
'' as "ATTRIBUTE_TIMESTAMP1",
'' as "ATTRIBUTE_TIMESTAMP2",
'' as "ATTRIBUTE_TIMESTAMP3",
'' as "ATTRIBUTE_TIMESTAMP4",
'' as "ATTRIBUTE_TIMESTAMP5",
'' as "ATTRIBUTE_TIMESTAMP6",
'' as "ATTRIBUTE_TIMESTAMP7",
'' as "ATTRIBUTE_TIMESTAMP8",
'' as "ATTRIBUTE_TIMESTAMP9",
'' as "ATTRIBUTE_TIMESTAMP10",
'' as "Unit Weight",
'' as "Weight UOM",
'' as "Unit Volumn",
'' as "Volume UOM Name",
'' as "Template Name",
'' as "ITEM_ATTRIBUTE_CATEGORY",
'' as "ITEM_ATTRIBUTE1",
'' as "ITEM_ATTRIBUTE2",
'' as "ITEM_ATTRIBUTE3",
'' as "ITEM_ATTRIBUTE4",
'' as "ITEM_ATTRIBUTE5",
'' as "ITEM_ATTRIBUTE6",
'' as "ITEM_ATTRIBUTE7",
'' as "ITEM_ATTRIBUTE8",
'' as "ITEM_ATTRIBUTE9",
'' as "ITEM_ATTRIBUTE10",
'' as "ITEM_ATTRIBUTE11",
'' as "ITEM_ATTRIBUTE12",
'' as "ITEM_ATTRIBUTE13",
'' as "ITEM_ATTRIBUTE14",
'' as "ITEM_ATTRIBUTE15",
PROCUREMENT_BUSINESS_UNIT_TL.NAME as "Source Agreement Procurement BU",
BPA.SEGMENT1 as "Source_agreement",
pla.line_num as "Source Agreement Line",
'' as "Discount Type Code",
'' as "Discount",
'' as "Discount Reason",
'' as "Maximum Retainage Amount",
'' as "Pricing UOM"


FROM
PO_LINES_ALL LINE
    left join PO_LINE_LOCATIONS_ALL LINE_LOCATION
        on LINE.PO_LINE_ID = LINE_LOCATION.PO_LINE_ID
    left join PO_HEADERS_ALL HEADER
        on LINE.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_HEADERS_ALL BPA
        on LINE_LOCATION.FROM_HEADER_ID = BPA.PO_HEADER_ID

    left join PO_LINES_ALL PLA
        ON LINE_LOCATION.FROM_HEADER_ID = PLA.PO_HEADER_ID
        AND LINE_LOCATION.FROM_LINE_ID = PLA.PO_LINE_ID

    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and LINE.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    left join PO_LINE_TYPES_B LINE_TYPE
        on LINE.LINE_TYPE_ID = LINE_TYPE.LINE_TYPE_ID
    left join EGP_CATEGORIES_TL CATEGORIES
        on LINE.CATEGORY_ID = CATEGORIES.CATEGORY_ID
    LEFT JOIN egp_system_items EGP
        on LINE.ITEM_ID = EGP.INVENTORY_ITEM_ID
    left join PO_UN_NUMBERS_B UN_NUMBER
        on LINE.UN_NUMBER_ID = UN_NUMBER.UN_NUMBER_ID
    left join HR_LOCATIONS_ALL SHIP_TO_LOCATION
        on LINE_LOCATION.SHIP_TO_LOCATION_ID = SHIP_TO_LOCATION.LOCATION_ID
    left join PO_DISTRIBUTIONS_ALL DISTRIBUTION
        ON LINE_LOCATION.LINE_LOCATION_ID = DISTRIBUTION.LINE_LOCATION_ID  
    left join GL_CODE_COMBINATIONS COMBINATIONS
        on DISTRIBUTION.CODE_COMBINATION_ID = COMBINATIONS.CODE_COMBINATION_ID
    left join HR_ORGANIZATION_UNITS_F_TL PROCUREMENT_BUSINESS_UNIT_TL
        on HEADER.PRC_BU_ID = PROCUREMENT_BUSINESS_UNIT_TL.ORGANIZATION_ID
    left join INV_ORG_PARAMETERS SHIP_TO_ORGANIZATION
        on LINE_LOCATION.SHIP_TO_ORGANIZATION_ID = SHIP_TO_ORGANIZATION.ORGANIZATION_ID
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) BUYER_NAME
        on DISTRIBUTION.DELIVER_TO_PERSON_ID = BUYER_NAME.PERSON_ID
    left join POR_REQ_DISTRIBUTIONS_ALL PRDA
        on DISTRIBUTION.REQ_DISTRIBUTION_ID = PRDA.DISTRIBUTION_ID
    left join POR_REQUISITION_LINES_ALL PRLA
        on PRDA.REQUISITION_LINE_ID = PRLA.REQUISITION_LINE_ID
    left join POR_REQUISITION_HEADERS_ALL PRHA
        on PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID
    

    left join PO_DOCUMENT_TYPES_ALL_TL pdt
        on BPA.type_lookup_code = pdt.DOCUMENT_SUBTYPE


where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and HEADER.segment1 ='PUSA9020023241'
    and LINE_LOCATION.ASSESSABLE_VALUE <> '0'

