select

'28032023' as "Import Batch Identifier",
EXTERNAL_PAYEE.EXT_PAYEE_ID as "Payee Identifier",
-- BUSINESS_UNIT -- ORG_ID -- none,
VENDOR.PARTY_NUMBER as VENDOR_NUM,
VENDOR_SITE.VENDOR_SITE_CODE,
EXTERNAL_PAYEE.EXCLUSIVE_PAYMENT_FLAG,
EXTERNAL_PAYEE.DEFAULT_PAYMENT_METHOD_CODE,
EXTERNAL_PAYEE.DELIVERY_CHANNEL_CODE,
EXTERNAL_PAYEE.SETTLEMENT_PRIORITY,
EXTERNAL_PAYEE.REMIT_ADVICE_DELIVERY_METHOD,
EXTERNAL_PAYEE.REMIT_ADVICE_EMAIL,
-- EXTERNAL_PAYEE.REMIT_ADVICE_FAX,
-- EXTERNAL_PAYEE.BANK_INSTRUCTION1_CODE,
-- EXTERNAL_PAYEE.BANK_INSTRUCTION2_CODE,
-- EXTERNAL_PAYEE.BANK_INSTRUCTION_DETAILS,
-- EXTERNAL_PAYEE.PAYMENT_REASON_CODE,
-- EXTERNAL_PAYEE.PAYMENT_REASON_COMMENTS,
-- EXTERNAL_PAYEE.PAYMENT_TEXT_MESSAGE1,
-- EXTERNAL_PAYEE.PAYMENT_TEXT_MESSAGE2,
-- EXTERNAL_PAYEE.PAYMENT_TEXT_MESSAGE3,
EXTERNAL_PAYEE.BANK_CHARGE_BEARER

from

IBY_EXTERNAL_PAYEES_ALL EXTERNAL_PAYEE
    left join POZ_SUPPLIER_SITES_ALL_M VENDOR_SITE
        on EXTERNAL_PAYEE.SUPPLIER_SITE_ID = VENDOR_SITE.VENDOR_SITE_ID
    left join POZ_SUPPLIERS SUPPLIER
        on VENDOR_SITE.VENDOR_ID = SUPPLIER.VENDOR_ID
    left join HZ_PARTIES VENDOR
        on SUPPLIER.PARTY_ID = VENDOR.PARTY_ID