select distinct

LINE.PO_LINE_ID as "Interface Line Key" ,
LINE.PO_HEADER_ID as "Interface Header Key",
'ADD' as "Action",
LINE.LINE_NUM as "Line",
LINE_TYPE.LINE_TYPE_CODE as "Line Type",
-- LINE.ITEM_NUMBER as "Item",
REPLACE(TRIM(LINE.ITEM_DESCRIPTION),CHR(10),' ') as "Item Description",
-- LINE.ITEM_REVISION as "Item Revision",
CATEGORIES.category_name as "Category name",
--LINE.category_id as "Category ID",
LINE.AMOUNT as "Amount",
LINE.QUANTITY as "Quantity",
-- LINE.SHIPPING_UOM_CODE as "UOM",
LINE.UNIT_PRICE as "Price",
-- LINE.SECONDARY_QUANTITY  as "SECONDARY QUANTITY",
--LINE.SECONDARY_UOM_CODE as "Secondary UOM",
LINE.VENDOR_PRODUCT_NUM as "Supplier Item",
LINE.NEGOTIATED_BY_PREPARER_FLAG as "Negotiated",
-- HAZARD.HAZARD_CLASS_CODE as "HAZARD CLASS",
-- UN_NUMBER.UN_NUMBER_CODE as "UN_NUMBER", -- UN TABLE IS EMPTY
-- REPLACE(TRIM(LINE.NOTE_TO_VENDOR),CHR(10),' ') as "Note to Supplier",
REPLACE(TRIM(HEADER.NOTE_TO_RECEIVER),CHR(10),' ') as "Note to Receiver",
-- LINE.ATTRIBUTE_CATEGORY as "ATTRIBUTE_CATEGORY",
LINE.ATTRIBUTE1,
LINE.ATTRIBUTE2,
LINE.ATTRIBUTE3
-- LINE.ATTRIBUTE4,
-- LINE.ATTRIBUTE5,
-- LINE.ATTRIBUTE6,
-- LINE.ATTRIBUTE7,
-- LINE.ATTRIBUTE8,
-- LINE.ATTRIBUTE9,
-- LINE.ATTRIBUTE10,
-- LINE.ATTRIBUTE11,
-- LINE.ATTRIBUTE12,
-- LINE.ATTRIBUTE13,
-- LINE.ATTRIBUTE14,
-- LINE.ATTRIBUTE15,
-- LINE.ATTRIBUTE16,
-- LINE.ATTRIBUTE17,
-- LINE.ATTRIBUTE18,
-- LINE.ATTRIBUTE19,
-- LINE.ATTRIBUTE20,
-- LINE.ATTRIBUTE_DATE1, 
-- LINE.ATTRIBUTE_DATE2, 
-- LINE.ATTRIBUTE_DATE3, 
-- LINE.ATTRIBUTE_DATE4, 
-- LINE.ATTRIBUTE_DATE5, 
-- LINE.ATTRIBUTE_DATE6, 
-- LINE.ATTRIBUTE_DATE7, 
-- LINE.ATTRIBUTE_DATE8, 
-- LINE.ATTRIBUTE_DATE9, 
-- LINE.ATTRIBUTE_DATE10,
-- LINE.ATTRIBUTE_NUMBER1,
-- LINE.ATTRIBUTE_NUMBER2,
-- LINE.ATTRIBUTE_NUMBER3,
-- LINE.ATTRIBUTE_NUMBER4,
-- LINE.ATTRIBUTE_NUMBER5,
-- LINE.ATTRIBUTE_NUMBER6,
-- LINE.ATTRIBUTE_NUMBER7,
-- LINE.ATTRIBUTE_NUMBER8,
-- LINE.ATTRIBUTE_NUMBER9,
-- LINE.ATTRIBUTE_NUMBER10,
-- LINE.ATTRIBUTE_TIMESTAMP1,
-- LINE.ATTRIBUTE_TIMESTAMP2,
-- LINE.ATTRIBUTE_TIMESTAMP3,
-- LINE.ATTRIBUTE_TIMESTAMP4,
-- LINE.ATTRIBUTE_TIMESTAMP5,
-- LINE.ATTRIBUTE_TIMESTAMP6,
-- LINE.ATTRIBUTE_TIMESTAMP7,
-- LINE.ATTRIBUTE_TIMESTAMP8,
-- LINE.ATTRIBUTE_TIMESTAMP9,
-- LINE.ATTRIBUTE_TIMESTAMP10,
--Unit_Weight as "Unit Weight",
--WEIGHT_UOM_CODE as "Weight UOM",
--VOLUME_UNIT_OF_ME as "Volume UOM Name",
--Template_Name as "Template Name",
--ITEM_ATTRIBUTE_CATEGORY as "ITEM_ATTRIBUTE_CATEGORY",
--ITEM_ATTRIBUTE1,
--ITEM_ATTRIBUTE2,
--ITEM_ATTRIBUTE3,
--ITEM_ATTRIBUTE4,
--ITEM_ATTRIBUTE5,
--ITEM_ATTRIBUTE6,
--ITEM_ATTRIBUTE7,
--ITEM_ATTRIBUTE8,
--ITEM_ATTRIBUTE9,
--ITEM_ATTRIBUTE10,
--ITEM_ATTRIBUTE11,
--ITEM_ATTRIBUTE12,
--ITEM_ATTRIBUTE13,
--ITEM_ATTRIBUTE14,
--ITEM_ATTRIBUTE15,
--SOURCE_AGREEMENT_PRC_BU_NAME as "Source Agreement Procurement BU",
--Source_Agreement as "Source Agreement",
--QUANTITY_COMMITTED as "Source Agreement Line",
-- LINE.DISCOUNT_TYPE as "Discount Type Code",
-- LINE.DISCOUNT as "Discount",
-- LINE.DISCOUNT_REASON as "Discount Reason",
-- LINE.MAX_RETAINAGE_AMOUNT as "Maximum Retainage Amount",
-- LINE.UOM_CODE as "Pricing UOM"

from
PO_LINE_LOCATIONS_ALL LINE_LOCATION
    LEFT JOIN PO_LINES_ALL LINE
       ON LINE_LOCATION.PO_LINE_ID = LINE.PO_LINE_ID
    left join PO_HEADERS_ALL HEADER
        on LINE.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and LINE.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    left join PO_LINE_TYPES_B LINE_TYPE
        on LINE.LINE_TYPE_ID = LINE_TYPE.LINE_TYPE_ID
    left join EGP_CATEGORIES_TL CATEGORIES
        on LINE.CATEGORY_ID = CATEGORIES.CATEGORY_ID
    -- left join PO_HAZARD_CLASSES_B HAZARD
    --     on LINE.HAZARD_CLASS_ID = HAZARD.HAZARD_CLASS_ID
    -- left join EGP_SYSTEM_ITEMS_B ITEM
    --     on LINE.ITEM_ID = ITEM.INVENTORY_ITEM_ID
    left join PO_UN_NUMBERS_B UN_NUMBER
        on LINE.UN_NUMBER_ID = UN_NUMBER.UN_NUMBER_ID

where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and HEADER.TYPE_LOOKUP_CODE = 'STANDARD'
    and DOCUMENT_TYPE.DOCUMENT_TYPE_CODE = 'PO'
    and LINE.AMOUNT <> 0