select

DISTRIBUTION.PO_DISTRIBUTION_ID as "Interface Distribution Key",
DISTRIBUTION.LINE_LOCATION_ID  as  "Interface Line Location Key",
DISTRIBUTION.DISTRIBUTION_NUM as "Distribution",
DELIVER_TO_LOCATION.LOCATION_CODE as "Deliver-to Location",
REQUESTER_NAME.FULL_NAME as "Requester",
-- DISTRIBUTION.DESTINATION_SUBINVENTORY as "Subinventory",
DISTRIBUTION.AMOUNT_ORDERED as "Amount",
DISTRIBUTION.SHIPPING_UOM_QUANTITY as "Quantity",
COMBINATIONS.SEGMENT1 "CHARGE_ACCOUNT_SEGMENT1",
COMBINATIONS.SEGMENT2 "CHARGE_ACCOUNT_SEGMENT2", 
COMBINATIONS.SEGMENT3 "CHARGE_ACCOUNT_SEGMENT3", 
COMBINATIONS.SEGMENT4 "CHARGE_ACCOUNT_SEGMENT4", 
COMBINATIONS.SEGMENT5 "CHARGE_ACCOUNT_SEGMENT5", 
COMBINATIONS.SEGMENT6 "CHARGE_ACCOUNT_SEGMENT6", 
COMBINATIONS.SEGMENT7 "CHARGE_ACCOUNT_SEGMENT7", 
COMBINATIONS.SEGMENT8 "CHARGE_ACCOUNT_SEGMENT8", 
COMBINATIONS.SEGMENT9 "CHARGE_ACCOUNT_SEGMENT9" 
-- CHARGE_ACCOUNT_SEGMENT10, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT11, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT12, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT13, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT14, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT15, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT16, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT17, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT18, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT19, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT20, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT21, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT22, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT23, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT24, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT25, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT26, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT27, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT28, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT29, -- counts to 0
-- CHARGE_ACCOUNT_SEGMENT30, -- counts to 0
-- DISTRIBUTION.DESTINATION_CONTEXT as "DESTINATION_CONTEXT",
-- DISTRIBUTION.PJC_PROJECT_ID as "Project Number", -- counts to 0
-- DISTRIBUTION.PJC_TASK_ID as "Task Number", -- counts to 0
-- DISTRIBUTION.PJC_EXPENDITURE_ITEM_DATE as "Expenditure Item Date",
-- EXPENDITURE_TYPE  as "Expenditure Type", -- counts to 0
-- EXPENDITURE_ORGANIZATION as "Expenditure Organization", -- counts to 0
-- DISTRIBUTION.PJC_BILLABLE_FLAG as "Billable",
-- DISTRIBUTION.PJC_CAPITALIZABLE_FLAG as "Capitalizable",
-- DISTRIBUTION.PJC_WORK_TYPE_ID as "Work Type", -- counts to 0
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE1,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE2,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE3,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE4,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE5,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE6,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE7,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE8,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE9,
-- DISTRIBUTION.PJC_RESERVED_ATTRIBUTE10,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE1,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE2,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE3,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE4,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE5,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE6,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE7,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE8,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE9,
-- DISTRIBUTION.PJC_USER_DEF_ATTRIBUTE10,
-- DISTRIBUTION.Rate as "Rate",
-- DISTRIBUTION.Rate_Date as "Rate Date",
-- DISTRIBUTION.ATTRIBUTE_CATEGORY,
-- DISTRIBUTION.ATTRIBUTE1,
-- DISTRIBUTION.ATTRIBUTE2,
-- DISTRIBUTION.ATTRIBUTE3,
-- DISTRIBUTION.ATTRIBUTE4,
-- DISTRIBUTION.ATTRIBUTE5,
-- DISTRIBUTION.ATTRIBUTE6,
-- DISTRIBUTION.ATTRIBUTE7,
-- DISTRIBUTION.ATTRIBUTE8,
-- DISTRIBUTION.ATTRIBUTE9,
-- DISTRIBUTION.ATTRIBUTE10,
-- DISTRIBUTION.ATTRIBUTE11,
-- DISTRIBUTION.ATTRIBUTE12,
-- DISTRIBUTION.ATTRIBUTE13,
-- DISTRIBUTION.ATTRIBUTE14,
-- DISTRIBUTION.ATTRIBUTE15,
-- DISTRIBUTION.ATTRIBUTE16,
-- DISTRIBUTION.ATTRIBUTE17,
-- DISTRIBUTION.ATTRIBUTE18,
-- DISTRIBUTION.ATTRIBUTE19,
-- DISTRIBUTION.ATTRIBUTE20,
-- DISTRIBUTION.ATTRIBUTE_DATE1,
-- DISTRIBUTION.ATTRIBUTE_DATE2,
-- DISTRIBUTION.ATTRIBUTE_DATE3,
-- DISTRIBUTION.ATTRIBUTE_DATE4,
-- DISTRIBUTION.ATTRIBUTE_DATE5,
-- DISTRIBUTION.ATTRIBUTE_DATE6,
-- DISTRIBUTION.ATTRIBUTE_DATE7,
-- DISTRIBUTION.ATTRIBUTE_DATE8,
-- DISTRIBUTION.ATTRIBUTE_DATE9,
-- DISTRIBUTION.ATTRIBUTE_DATE10,
-- DISTRIBUTION.ATTRIBUTE_NUMBER1,
-- DISTRIBUTION.ATTRIBUTE_NUMBER2,
-- DISTRIBUTION.ATTRIBUTE_NUMBER3,
-- DISTRIBUTION.ATTRIBUTE_NUMBER4,
-- DISTRIBUTION.ATTRIBUTE_NUMBER5,
-- DISTRIBUTION.ATTRIBUTE_NUMBER6,
-- DISTRIBUTION.ATTRIBUTE_NUMBER7,
-- DISTRIBUTION.ATTRIBUTE_NUMBER8,
-- DISTRIBUTION.ATTRIBUTE_NUMBER9,
-- DISTRIBUTION.ATTRIBUTE_NUMBER10,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP1,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP2,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP3,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP4,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP5,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP6,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP7,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP8,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP9,
-- DISTRIBUTION.ATTRIBUTE_TIMESTAMP10,
-- DELIVER_TO_PERSON_EMAIL_ADDR as "Requester E-mail",
-- DISTRIBUTION.BUDGET_DATE as "Budget Date",
-- DISTRIBUTION.PJC_CONTRACT_ID as "Contract Number", -- counts to 0
-- PJC_FUNDING_SOURCE as "Funding Source",
-- DISTRIBUTION.GLOBAL_ATTRIBUTE1 as "GLOBAL_ATTRIBUTE1"

from

PO_DISTRIBUTIONS_ALL DISTRIBUTION
    left join GL_CODE_COMBINATIONS COMBINATIONS
        on DISTRIBUTION.CODE_COMBINATION_ID = COMBINATIONS.CODE_COMBINATION_ID
    left join PO_HEADERS_ALL HEADER
        on DISTRIBUTION.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and DISTRIBUTION.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    left join HR_LOCATIONS_ALL DELIVER_TO_LOCATION
        on DISTRIBUTION.DELIVER_TO_LOCATION_ID = DELIVER_TO_LOCATION.LOCATION_ID
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) REQUESTER_NAME
        on HEADER.AGENT_ID = REQUESTER_NAME.PERSON_ID

where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and HEADER.TYPE_LOOKUP_CODE = 'STANDARD'
    and DOCUMENT_TYPE.DOCUMENT_TYPE_CODE = 'PO'
    and DISTRIBUTION.AMOUNT_ORDERED <> 0
