select distinct

HEADER.PO_HEADER_ID as "Interface Header Key",
'ORIGINAL' as "Action",
'100' as "Batch ID",
-- HEADER.INTERFACE_SOURCE_CODE AS "Import Source",
'BYPASS' as "Approval Action",
-- HEADER.VENDOR_ORDER_NUM as "Order",
HEADER.TYPE_LOOKUP_CODE as "Document Type Code",
DOCUMENT_STYLE.STYLE_NAME as "Style",
PROCUREMENT_BUSINESS_UNIT_TL.NAME as "Procurement BU",
REQUISITIONING_BU_TL.NAME as "Requisitioning BU",
-- HEADER.SOLDTO_BU_ID as Sold_to_Legal_Entity, -- counts to 0
BILL_TO_BU_TL.NAME as "Bill-to BU",
BUYER_NAME.FULL_NAME as "Buyer",
HEADER.CURRENCY_CODE as "Currency Code",
-- HEADER.RATE as RATE,
-- HEADER.RATE_TYPE as RATE_TYPE,
-- HEADER.RATE_DATE as RATE_DATE,
REPLACE(TRIM(HEADER.COMMENTS),CHR(10),' ')  as "Description",
BILL_TO_LOCATION.LOCATION_CODE as "Bill To Location",
SHIP_TO_LOCATION.LOCATION_CODE as "Ship-to Location",
SUPPLIER.VENDOR_NAME as "Supplier",
SUPPLIER.SEGMENT1 as "Supplier Number",
SUPPLIER_SITE.VENDOR_SITE_CODE as "Supplier Site",
-- HEADER.VENDOR_CONTACT_ID AS "Supplier Contact", -- counts to 0
-- HEADER.VENDOR_ORDER_NUM as "Supplier Order",
-- HEADER.FOB_LOOKUP_CODE as "Fob",
FREIGHT_CARRIER.PARTY_NAME as "Carrier", 
-- HEADER.FREIGHT_TERMS_LOOKUP_CODE as "Freight Terms",
-- HEADER.PAY_ON_CODE as "Pay On Code",
TERM_TL.NAME as "Payment Terms",
VERSION.ORIGINATOR_ROLE as "Initiating Party",
-- VERSION.CHANGE_ORDER_DESC as "Change Order Description",
HEADER.ACCEPTANCE_REQUIRED_FLAG as "Required Acknowledgment",
-- HEADER.ACCEPTANCE_WITHIN_DAYS as "Acknowledge Within (Days)",
HEADER.SUPPLIER_NOTIF_METHOD as "Communication Method",
-- HEADER.FAX as "Fax",
HEADER.EMAIL_ADDRESS as "To Email",
HEADER.CONFIRMING_ORDER_FLAG as "Confirming order",
REPLACE(TRIM(HEADER.NOTE_TO_VENDOR),CHR(10),' ') AS "Note to Supplier",
REPLACE(TRIM(HEADER.NOTE_TO_RECEIVER),CHR(10),' ') AS "Note to Receiver",
HEADER.DEFAULT_TAXATION_COUNTRY AS "Default Taxation Country Code",
-- HEADER.TAX_DOCUMENT_SUBTYPE AS Tax_Document_Subtype_Code,
-- HEADER.ATTRIBUTE_CATEGORY,
HEADER.ATTRIBUTE1,
-- HEADER.ATTRIBUTE2,
-- HEADER.ATTRIBUTE3,
-- HEADER.ATTRIBUTE4,
-- HEADER.ATTRIBUTE5,
-- HEADER.ATTRIBUTE6,
-- HEADER.ATTRIBUTE7,
-- HEADER.ATTRIBUTE8,
-- HEADER.ATTRIBUTE9,
-- HEADER.ATTRIBUTE10,
-- HEADER.ATTRIBUTE11,
-- HEADER.ATTRIBUTE12,
-- HEADER.ATTRIBUTE13,
-- HEADER.ATTRIBUTE14,
-- HEADER.ATTRIBUTE15,
-- HEADER.ATTRIBUTE16,
-- HEADER.ATTRIBUTE17,
-- HEADER.ATTRIBUTE18,
-- HEADER.ATTRIBUTE19,
-- HEADER.ATTRIBUTE20,
-- HEADER.ATTRIBUTE_DATE1,
-- HEADER.ATTRIBUTE_DATE2,
-- HEADER.ATTRIBUTE_DATE3,
-- HEADER.ATTRIBUTE_DATE4,
-- HEADER.ATTRIBUTE_DATE5,
-- HEADER.ATTRIBUTE_DATE6,
-- HEADER.ATTRIBUTE_DATE7,
-- HEADER.ATTRIBUTE_DATE8,
-- HEADER.ATTRIBUTE_DATE9,
-- HEADER.ATTRIBUTE_DATE10,
-- HEADER.ATTRIBUTE_NUMBER1,
-- HEADER.ATTRIBUTE_NUMBER2,
-- HEADER.ATTRIBUTE_NUMBER3,
-- HEADER.ATTRIBUTE_NUMBER4,
-- HEADER.ATTRIBUTE_NUMBER5,
-- HEADER.ATTRIBUTE_NUMBER6,
-- HEADER.ATTRIBUTE_NUMBER7,
-- HEADER.ATTRIBUTE_NUMBER8,
-- HEADER.ATTRIBUTE_NUMBER9,
-- HEADER.ATTRIBUTE_NUMBER10,
-- HEADER.ATTRIBUTE_TIMESTAMP1,
-- HEADER.ATTRIBUTE_TIMESTAMP2,
-- HEADER.ATTRIBUTE_TIMESTAMP3,
-- HEADER.ATTRIBUTE_TIMESTAMP4,
-- HEADER.ATTRIBUTE_TIMESTAMP5,
-- HEADER.ATTRIBUTE_TIMESTAMP6,
-- HEADER.ATTRIBUTE_TIMESTAMP7,
-- HEADER.ATTRIBUTE_TIMESTAMP8,
-- HEADER.ATTRIBUTE_TIMESTAMP9,
-- HEADER.ATTRIBUTE_TIMESTAMP10,
BUYER_EMAIL.EMAIL_ADDRESS as "Buyer E-mail",
-- HEADER.MODE_OF_TRANSPORT as "Mode of Transport",
-- HEADER.FIRST_PTY_REG_ID AS First_Party_Tax_Registration_Number, -- counts to 0
-- HEADER.THIRD_PTY_REG_ID AS Third_Party_Tax_Registration_Number, -- counts to 0
HEADER.BUYER_MANAGED_TRANSPORT_FLAG as "Buyer Managed Transportation"
-- Master Contract Number (MASTER_CONTRACT_NUMBER)
-- Master Contract Type (MASTER_CONTRACT_TYPE)
-- HEADER.CC_EMAIL_ADDRESS as "CC Email",
-- HEADER.BCC_EMAIL_ADDRESS as "BCC EMAIL",
-- HEADER.GLOBAL_ATTRIBUTE1,
-- HEADER.GLOBAL_ATTRIBUTE2,
-- HEADER.GLOBAL_ATTRIBUTE3,
-- HEADER.GLOBAL_ATTRIBUTE4,
-- HEADER.GLOBAL_ATTRIBUTE5,
-- HEADER.GLOBAL_ATTRIBUTE6 

from
PO_LINE_LOCATIONS_ALL LINE_LOCATION
    
    LEFT JOIN PO_LINES_ALL LINE
        ON LINE_LOCATION.PO_LINE_ID = LINE.PO_LINE_ID
    left join PO_HEADERS_ALL HEADER
        on LINE.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
    left join PO_DOC_STYLE_HEADERS DOCUMENT_STYLE
        on HEADER.STYLE_ID = DOCUMENT_STYLE.STYLE_ID
    left join HR_ORGANIZATION_UNITS_F_TL PROCUREMENT_BUSINESS_UNIT_TL
        on HEADER.PRC_BU_ID = PROCUREMENT_BUSINESS_UNIT_TL.ORGANIZATION_ID
        and PROCUREMENT_BUSINESS_UNIT_TL.LANGUAGE = 'US'
    left join HR_ORGANIZATION_UNITS_F_TL REQUISITIONING_BU_TL
        on HEADER.REQ_BU_ID = REQUISITIONING_BU_TL.ORGANIZATION_ID
        and REQUISITIONING_BU_TL.LANGUAGE = 'US'
    left join HR_ORGANIZATION_UNITS_F_TL BILL_TO_BU_TL
        on HEADER.BILLTO_BU_ID = BILL_TO_BU_TL.ORGANIZATION_ID
        and BILL_TO_BU_TL.LANGUAGE = 'US'
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) BUYER_NAME
        on HEADER.AGENT_ID = BUYER_NAME.PERSON_ID
    left join POZ_SUPPLIERS_SIMPLE_V SUPPLIER
        on HEADER.VENDOR_ID = SUPPLIER.VENDOR_ID
    left join POZ_SUPPLIER_SITES_ALL_M SUPPLIER_SITE
        on HEADER.VENDOR_SITE_ID = SUPPLIER_SITE.VENDOR_SITE_ID
    left join HZ_PARTIES FREIGHT_CARRIER
        on HEADER.CARRIER_ID = FREIGHT_CARRIER.PARTY_ID
    left join AP_TERMS_TL TERM_TL
        on HEADER.TERMS_ID = TERM_TL.TERM_ID
        and TERM_TL.LANGUAGE = 'US'
    left join HR_LOCATIONS_ALL BILL_TO_LOCATION
        on HEADER.BILL_TO_LOCATION_ID = BILL_TO_LOCATION.LOCATION_ID
    left join HR_LOCATIONS_ALL SHIP_TO_LOCATION
        on HEADER.SHIP_TO_LOCATION_ID = SHIP_TO_LOCATION.LOCATION_ID
    left join (
        select
            PO_HEADER_ID,
            ORIGINATOR_ROLE,
            CHANGE_ORDER_DESC
        from
            PO_VERSIONS
        where
            CO_SEQUENCE = 0
    ) VERSION
        on HEADER.PO_HEADER_ID = VERSION.PO_HEADER_ID
    left join (
        select 
        distinct
            PERSON_ID,
            EMAIL_ADDRESS
        from
            PER_EMAIL_ADDRESSES
    ) BUYER_EMAIL
        on HEADER.AGENT_ID = BUYER_EMAIL.PERSON_ID

where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and HEADER.TYPE_LOOKUP_CODE = 'STANDARD'
    and DOCUMENT_TYPE.DOCUMENT_TYPE_CODE = 'PO'
    and LINE.AMOUNT <> 0
   
