select distinct

LINE_LOCATION.LINE_LOCATION_ID  as "Interface Line Location Key",
LINE.PO_LINE_ID as "Interface Line Key",
LINE_LOCATION.SHIPMENT_NUM as "Schedule",
SHIP_TO_LOCATION.LOCATION_CODE as "Ship-to Location",
SHIP_TO_ORGANIZATION.ORGANIZATION_CODE as "Ship-to Organization",
LINE_LOCATION.ASSESSABLE_VALUE as "Amount",
LINE_LOCATION.SHIPPING_UOM_QUANTITY as "Quantity",
TO_CHAR(LINE_LOCATION.NEED_BY_DATE, 'YYYY/MM/DD') as "Need-by Date",
TO_CHAR(LINE_LOCATION.PROMISED_DATE, 'YYYY/MM/DD') as "Promised Date",
LINE_LOCATION.SECONDARY_QUANTITY_RECEIVED as "Secondary Quantity",
-- LINE_LOCATION.SECONDARY_UOM_CODE as "Secondary UOM",
LINE_LOCATION.DESTINATION_TYPE_CODE as "Destination Type Code",
LINE_LOCATION.ACCRUE_ON_RECEIPT_FLAG as "Accrue at receipt",
LINE_LOCATION.ALLOW_SUBSTITUTE_RECEIPTS_FLAG as "Allow substitute receipts",
LINE_LOCATION.ASSESSABLE_VALUE as "Assessable Value",
LINE_LOCATION.DAYS_EARLY_RECEIPT_ALLOWED as "Early Receipt Tolerance in Days",
LINE_LOCATION.DAYS_LATE_RECEIPT_ALLOWED  as "Late Receipt Tolerance in Days",
LINE_LOCATION.ENFORCE_SHIP_TO_LOCATION_CODE as "Enforce Ship to Location Code",
LINE_LOCATION.INSPECTION_REQUIRED_FLAG  as "Inspection Required",
LINE_LOCATION.RECEIPT_REQUIRED_FLAG as "Receipt Required",
LINE_LOCATION.INVOICE_CLOSE_TOLERANCE as "Invoice Close Tolerance Percent",
LINE_LOCATION.RECEIVE_CLOSE_TOLERANCE as "Receipt Close Tolerance Percent",
LINE_LOCATION.QTY_RCV_TOLERANCE as "Qty Rcv Tolerance",
LINE_LOCATION.QTY_RCV_EXCEPTION_CODE as "Qty Rcv Exception Code",
LINE_LOCATION.RECEIPT_DAYS_EXCEPTION_CODE as "Receipt Days Exception Code",
CASE LINE_LOCATION.RECEIVING_ROUTING_ID 
        WHEN 1 THEN 'Standard Receipt'
        WHEN 2 THEN 'Inspection Required'
        WHEN 3 THEN 'Direct Delivery'
        ELSE 'Unknown'
    END AS "Receipt Routing",
LINE_LOCATION.NOTE_TO_RECEIVER  as "Note to receiver",
LINE_LOCATION.INPUT_TAX_CLASSIFICATION_CODE as "Tax Classification",
LINE_LOCATION.LINE_INTENDED_USE as "Intended Use",
LINE_LOCATION.PRODUCT_TYPE as "Product Type Code",
LINE_LOCATION.TRX_BUSINESS_CATEGORY as "Transaction Business Category Code",
-- LINE_LOCATION.USER_DEFINED_FISC_CLASS as "User-Defined Fiscal Classification Code",


-- LINE_LOCATION.ATTRIBUTE_CATEGORY,
-- LINE_LOCATION.ATTRIBUTE1,
-- LINE_LOCATION.ATTRIBUTE2,
-- LINE_LOCATION.ATTRIBUTE3,
-- LINE_LOCATION.ATTRIBUTE4,
-- LINE_LOCATION.ATTRIBUTE5,
-- LINE_LOCATION.ATTRIBUTE6,
-- LINE_LOCATION.ATTRIBUTE7,
-- LINE_LOCATION.ATTRIBUTE8,
-- LINE_LOCATION.ATTRIBUTE9,
-- LINE_LOCATION.ATTRIBUTE10,
-- LINE_LOCATION.ATTRIBUTE11,
-- LINE_LOCATION.ATTRIBUTE12,
-- LINE_LOCATION.ATTRIBUTE13,
-- LINE_LOCATION.ATTRIBUTE14,
-- LINE_LOCATION.ATTRIBUTE15,
-- LINE_LOCATION.ATTRIBUTE16,
-- LINE_LOCATION.ATTRIBUTE17,
-- LINE_LOCATION.ATTRIBUTE18,
-- LINE_LOCATION.ATTRIBUTE19,
-- LINE_LOCATION.ATTRIBUTE20,
-- LINE_LOCATION.ATTRIBUTE_DATE1, 
-- LINE_LOCATION.ATTRIBUTE_DATE2, 
-- LINE_LOCATION.ATTRIBUTE_DATE3, 
-- LINE_LOCATION.ATTRIBUTE_DATE4, 
-- LINE_LOCATION.ATTRIBUTE_DATE5, 
-- LINE_LOCATION.ATTRIBUTE_DATE6, 
-- LINE_LOCATION.ATTRIBUTE_DATE7, 
-- LINE_LOCATION.ATTRIBUTE_DATE8, 
-- LINE_LOCATION.ATTRIBUTE_DATE9, 
-- LINE_LOCATION.ATTRIBUTE_DATE10,
-- LINE_LOCATION.ATTRIBUTE_NUMBER1,
-- LINE_LOCATION.ATTRIBUTE_NUMBER2,
-- LINE_LOCATION.ATTRIBUTE_NUMBER3,
-- LINE_LOCATION.ATTRIBUTE_NUMBER4,
-- LINE_LOCATION.ATTRIBUTE_NUMBER5,
-- LINE_LOCATION.ATTRIBUTE_NUMBER6,
-- LINE_LOCATION.ATTRIBUTE_NUMBER7,
-- LINE_LOCATION.ATTRIBUTE_NUMBER8,
-- LINE_LOCATION.ATTRIBUTE_NUMBER9,
-- LINE_LOCATION.ATTRIBUTE_NUMBER10,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP1,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP2,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP3,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP4,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP5,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP6,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP7,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP8,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP9,
-- LINE_LOCATION.ATTRIBUTE_TIMESTAMP10,
LINE_LOCATION.CARRIER_ID as "Carrier",
HEADER.MODE_OF_TRANSPORT as "Mode of Transport",
LINE_LOCATION.SERVICE_LEVEL as "Service Level",
LINE_LOCATION.FINAL_DISCHARGE_LOCATION_ID as "Final discharge location code",
-- LINE_LOCATION.REQUESTED_SHIP_DATE  as "Requested Ship Date",
TO_CHAR(LINE_LOCATION.PROMISED_DATE, 'YYYY/MM/DD') as "Promised Ship  Date",
TO_CHAR(LINE_LOCATION.NEED_BY_DATE, 'YYYY/MM/DD') as "Requested Delivery Date",
case LINE_LOCATION.MATCH_OPTION
    when 'P' then 'Order'
    when 'R' then 'Receipt'
    else NULL
end as "Invoice Match Option",
TO_CHAR(LINE_LOCATION.PROMISED_DATE, 'YYYY/MM/DD') as "Promised Delivery Date"

-- LINE_LOCATION.PRODUCT_CATEGORY as "Product Category Code",
-- LINE_LOCATION.PRODUCT_FISC_CLASSIFICATION as "Product Fiscal Classification",
-- FINAL_DISCHARGE_LOCATION.LOCATION_NAME as "Final discharge location code", -- counts to 0
-- LINE_LOCATION.PROMISED_SHIP_DATE as "Promised Ship Date",
-- LINE_LOCATION.RETAINAGE_RATE as "Retainage Rate (%)",
-- INVOICE_MATCH_OPTION as "Invoice Match Option",
-- LINE_LOCATION.GLOBAL_ATTRIBUTE1 as "GLOBAL_ATTRIBUTE1",
-- LINE_LOCATION.GLOBAL_ATTRIBUTE_NUMBER1 as "GLOBAL_ATTRIBUTE_NUMBER1"

from

PO_LINE_LOCATIONS_ALL LINE_LOCATION 
    LEFT JOIN PO_LINES_ALL LINE
        ON LINE_LOCATION.PO_LINE_ID = LINE.PO_LINE_ID
    left join PO_DISTRIBUTIONS_ALL DISTRIBUTION
        ON LINE_LOCATION.LINE_LOCATION_ID = DISTRIBUTION.LINE_LOCATION_ID
    left join PO_HEADERS_ALL HEADER
        on LINE_LOCATION.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join GL_CODE_COMBINATIONS COMBINATIONS
        on DISTRIBUTION.CODE_COMBINATION_ID = COMBINATIONS.CODE_COMBINATION_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and LINE_LOCATION.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    left join HR_LOCATIONS_ALL SHIP_TO_LOCATION
        on LINE_LOCATION.SHIP_TO_LOCATION_ID = SHIP_TO_LOCATION.LOCATION_ID
    left join INV_ORG_PARAMETERS SHIP_TO_ORGANIZATION
        on LINE_LOCATION.SHIP_TO_ORGANIZATION_ID = SHIP_TO_ORGANIZATION.ORGANIZATION_ID
    LEFT JOIN egp_system_items EGP
        on LINE.ITEM_ID = EGP.INVENTORY_ITEM_ID
    -- left join RCV_ROUTING_HEADERS RECEIVING_ROUTE
    --     on LINE_LOCATION.RECEIVING_ROUTING_ID = RECEIVING_ROUTE.SHIPMENT_HEADER_ID
    -- left join HR_LOCATIONS_ALL FINAL_DISCHARGE_LOCATION
    --     on LINE_LOCATION.FINAL_DISCHARGE_LOCATION_ID = SHIP_TO_LOCATION.LOCATION_ID
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) REQUESTER_NAME
        on HEADER.AGENT_ID = REQUESTER_NAME.PERSON_ID
where
    HEADER.DOCUMENT_STATUS ='OPEN'
and LINE_LOCATION.ASSESSABLE_VALUE <> '0'
