select distinct
HEADER.segment1 as "Order",
DISTRIBUTION.PO_DISTRIBUTION_ID as "Interface Distribution Key",
DISTRIBUTION.LINE_LOCATION_ID  as  "Interface Line Location Key",
DISTRIBUTION.DISTRIBUTION_NUM as "Distribution",
DISTRIBUTION.DESTINATION_SUBINVENTORY as "DESTINATION SUBINVENTORY",
LINE.LINE_NUM as "Line Number",
LINE_LOCATION.SHIPMENT_NUM as "Schedule Line Number",
REPLACE(TRIM(line.item_description),CHR(10),' ')  as "Description",
DISTRIBUTION.DISTRIBUTION_NUM as "Distribution Line Number",
case (DISTRIBUTION.QUANTITY_ORDERED - DISTRIBUTION.QUANTITY_CANCELLED) - DISTRIBUTION.QUANTITY_DELIVERED
    when 0 then 'Delivered'
    else 'Not Delivered'
end as "STATUS",
LINE_LOCATION.DESTINATION_TYPE_CODE as "Destination Type",
DELIVER_TO_LOCATION.LOCATION_CODE as "Deliver-to Location",
LINE_LOCATION.UOM_CODE as "UOM",
LINE_LOCATION.ASSESSABLE_VALUE as "ORDERED",
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT1 as "po_charge_account_SEGMENT1",
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT2 as "po_charge_account_SEGMENT2", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT3 as "po_charge_account_SEGMENT3", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT4 as "po_charge_account_SEGMENT4", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT5 as "po_charge_account_SEGMENT5", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT6 as "po_charge_account_SEGMENT6", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT7 as "po_charge_account_SEGMENT7", 
CHARGE_ACCOUNT_COMBINATIONS.SEGMENT8 as "po_charge_account_SEGMENT8",


ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT1 as "accrual_account_SEGMENT1",
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT2 as "accrual_account_SEGMENT2", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT3 as "accrual_account_SEGMENT3", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT4 as "accrual_account_SEGMENT4", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT5 as "accrual_account_SEGMENT5", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT6 as "accrual_account_SEGMENT6", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT7 as "accrual_account_SEGMENT7", 
ACCRUAL_ACCOUNT_COMBINATIONS.SEGMENT8 as "accrual_account_SEGMENT8",


VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT1 as "variace_account_SEGMENT1",
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT2 as "variace_account_SEGMENT2", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT3 as "variace_account_SEGMENT3", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT4 as "variace_account_SEGMENT4", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT5 as "variace_account_SEGMENT5", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT6 as "variace_account_SEGMENT6", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT7 as "variace_account_SEGMENT7", 
VARIANCE_ACCOUNT_COMBINATIONS.SEGMENT8 as "variace_account_SEGMENT8",

EGP.ITEM_NUMBER as "ITEM",
LINE.ITEM_REVISION as "REVISION",
DISTRIBUTION.PJC_PROJECT_ID as "Project Number",
DISTRIBUTION.PJC_TASK_ID as "Task Number",
DISTRIBUTION.PJC_EXPENDITURE_ITEM_DATE as "Expenditure Item Date",
DISTRIBUTION.PJC_EXPENDITURE_TYPE_ID as "Expenditure Type",
DISTRIBUTION.PJC_ORGANIZATION_ID as "Expenditure Organization",
LINE.CONTRACT_ID as "Contract Number",
DISTRIBUTION.RATE_DATE as "Conversion Date",
REQUESTER_NAME.FULL_NAME as "Requester",
HEADER.GROUP_REQUISITIONS as "REQUISITIONS",
DISTRIBUTION.REQ_LINE_REFERENCE_NUM as "Requisition Line",
LINE.TAX_EXCLUSIVE_PRICE as "TOTAL TAX",
LINE_LOCATION.ASSESSABLE_VALUE as "TOTAL / AMOUNT",
DISTRIBUTION.SHIPPING_UOM_QUANTITY as "Quantity"

from

PO_DISTRIBUTIONS_ALL DISTRIBUTION
    
    left join GL_CODE_COMBINATIONS CHARGE_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.CODE_COMBINATION_ID = CHARGE_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID
    
    left join GL_CODE_COMBINATIONS ACCRUAL_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.ACCRUAL_ACCOUNT_ID = ACCRUAL_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID
    
    left join GL_CODE_COMBINATIONS VARIANCE_ACCOUNT_COMBINATIONS
        on DISTRIBUTION.VARIANCE_ACCOUNT_ID = VARIANCE_ACCOUNT_COMBINATIONS.CODE_COMBINATION_ID

    left join PO_HEADERS_ALL HEADER
        on DISTRIBUTION.PO_HEADER_ID = HEADER.PO_HEADER_ID
    left join PO_DOCUMENT_TYPES_ALL_B DOCUMENT_TYPE
        on HEADER.TYPE_LOOKUP_CODE = DOCUMENT_TYPE.DOCUMENT_SUBTYPE
        and DISTRIBUTION.PRC_BU_ID = DOCUMENT_TYPE.PRC_BU_ID
    LEFT JOIN PO_LINE_LOCATIONS_ALL LINE_LOCATION
        ON DISTRIBUTION.LINE_LOCATION_ID = LINE_LOCATION.LINE_LOCATION_ID
    left join HR_LOCATIONS_ALL DELIVER_TO_LOCATION
        on DISTRIBUTION.DELIVER_TO_LOCATION_ID = DELIVER_TO_LOCATION.LOCATION_ID
    LEFT JOIN PO_LINES_ALL LINE
       ON LINE_LOCATION.PO_LINE_ID = LINE.PO_LINE_ID
    LEFT JOIN egp_system_items EGP
        on LINE.ITEM_ID = EGP.INVENTORY_ITEM_ID
    left join (
        select distinct
            PERSON_ID,
            FULL_NAME
        from
            PER_PERSON_NAMES_F
        where
            NAME_TYPE = 'US'
    ) REQUESTER_NAME
        on DISTRIBUTION.DELIVER_TO_PERSON_ID = REQUESTER_NAME.PERSON_ID
    left join EGP_CATEGORIES_TL CATEGORIES
        on LINE.CATEGORY_ID = CATEGORIES.CATEGORY_ID
where
    HEADER.DOCUMENT_STATUS = 'OPEN'
    and LINE_LOCATION.ASSESSABLE_VALUE <> '0'
    and HEADER.segment1 ='PUSA9070004853'


order by
    header.segment1,
    LINE.LINE_NUM,
    LINE_LOCATION.SHIPMENT_NUM,
    DISTRIBUTION.DISTRIBUTION_NUM
