SELECT ROWNUM INTERFACE_LINE_NUMBER,
A.*
FROM (
SELECT
CURRENCY_CODE,
FIXED_ASSETS_COST,
EXCHANGE_RATE

FROM 
FA_MC_MASS_RATES

    ) A
----- está completamente vazia no DEV2
----- it is completely empty in DEV2
