SELECT
    a.asset_number AS "INTERFACE LINE NUMBER",
    A."ASSET BOOK",
    A.ASSET_NUMBER,
    A.Total_YTD_DEPRN,
    A.DEPRN_RESERVE

FROM (
    SELECT
        BKCTRL.BOOK_TYPE_CODE AS "ASSET BOOK",
        favl.ASSET_NUMBER,
        SUM(FDS.YTD_DEPRN) AS Total_YTD_DEPRN,
        SUM(FDS.DEPRN_RESERVE) as DEPRN_RESERVE,
        ''as "TRANSACTION NAME",
        '' as "Tag Number"

    FROM
FA_BOOK_CONTROLS BKCTRL,
FA_BOOKS FABOOKS,
FA_ADDITIONS_VL favl,
FA_METHODS fm,
FA_CATEGORIES_VL FA_CATEGORY,
FA_ASSET_KEYWORDS ASSETKEYWORDS,
FA_DISTRIBUTION_HISTORY FA_DISTRIB,
FA_LOCATIONS FA_LOCATION,
--FA_TRANSACTION_HEADERS FT,
FA_CONVENTION_TYPES  CT ,
FA_ADDITIONS_B FA1,
FA_ADDITIONS_B FA2,
FA_DEPRN_PERIODS FDP,
fa_deprn_detail   FDS,
FA_ASSET_INVOICES FAI ,
FA_CATEGORY_BOOKS  FCB,
AP_INVOICES_ALL AIA,
GL_CODE_COMBINATIONS GCC,
POZ_SUPPLIERS PS
    WHERE
        favl.ASSET_ID = FDS.ASSET_ID
        AND favl.ASSET_NUMBER = '19115'
        AND FDP.PERIOD_COUNTER = FDS.PERIOD_COUNTER
        AND FDP.BOOK_TYPE_CODE = FDS.BOOK_TYPE_CODE
        AND FDS.BOOK_TYPE_CODE = FABOOKS.BOOK_TYPE_CODE
        AND FABOOKS.BOOK_TYPE_CODE = BKCTRL.BOOK_TYPE_CODE
        AND favl.ASSET_ID = FABOOKS.ASSET_ID
AND FABOOKS.METHOD_ID = fm.METHOD_ID(+)
AND favl.ASSET_CATEGORY_ID = FA_CATEGORY.CATEGORY_ID(+)
AND favl.ASSET_KEY_CCID = ASSETKEYWORDS.CODE_COMBINATION_ID(+)
AND FABOOKS.BOOK_TYPE_CODE = FA_DISTRIB.BOOK_TYPE_CODE(+)
AND favl.ASSET_ID = FA_DISTRIB.ASSET_ID(+)
AND FA_DISTRIB.LOCATION_ID = FA_LOCATION.LOCATION_ID(+)
---
AND FA2.ASSET_ID (+) = FA1.PARENT_ASSET_ID
AND AIA.INVOICE_ID(+)=FAI.INVOICE_ID
AND favl.ASSET_ID = FAI.ASSET_ID(+)
AND FABOOKS.BOOK_TYPE_CODE = FAI.BOOK_TYPE_CODE(+)
AND FCB.ASSET_CLEARING_ACCOUNT_CCID = GCC.CODE_COMBINATION_ID
AND FCB.BOOK_TYPE_CODE = BKCTRL.BOOK_TYPE_CODE
AND favl.ASSET_CATEGORY_ID = FCB.CATEGORY_ID
and fds.DISTRIBUTION_ID = FA_DISTRIB.DISTRIBUTION_ID
and FA_DISTRIB.book_type_code = fds.book_type_code
AND FABOOKS.CONVENTION_TYPE_ID = CT.CONVENTION_TYPE_ID(+)
AND FA1.ASSET_ID = favl.ASSET_ID
AND PS.VENDOR_ID(+) = AIA.VENDOR_ID
and NVL(FABOOKS.DATE_INEFFECTIVE , sysdate) >= sysdate
and NVL(FA_DISTRIB.DATE_INEFFECTIVE , sysdate) >= sysdate
AND FDP.PERIOD_COUNTER IN ( SELECT MAX(FDS1.PERIOD_COUNTER)
                             FROM FA_DEPRN_DETAIL FDS1
							 WHERE FDS.ASSET_ID = FDS1.ASSET_ID
                               AND FDS.BOOK_TYPE_CODE = FDS1.BOOK_TYPE_CODE )
    GROUP BY
        BKCTRL.BOOK_TYPE_CODE,
        favl.ASSET_NUMBER
) A